[[template]]
  src         = "${REMCO_TEMPLATE_DIR}/realm.properties"
  dst         = "${RUNDECK_HOME}/server/config/realm.properties"
  mode        = "0644"

  [backend]
    [backend.consul]
      nodes = ["${RUNDECK_CONSUL_HOST_PORT}"]
      onetime = true
      interval = 1
      keys = ["/"]
